### ISSUE TITLE
feat: setup base project

### ISSUE THREAD

**Issue by danielhe4rt** [basementdevs/scyllash#1]
This project will be made with Rust and `ratatui` crate. 

After the basic configurations, also bring a CI/CD to the repository in this first moment so we can maintain the codebase organized.

**Comment by Daniel-Boll** [comment]
The initial setup is done in the main branch already, @gvieira18 can go ahead with some CI/CD.

**Comment by gvieira18** [comment]
I added the minimal config to pull request #9.

Also, what do you guys think about the release flow? Is it full main branch, or do we have develop and main too, or do we just follow main but releases are requested manually through `workflow_dispatch`?

I see @Daniel-Boll has commented about providing binaries to download along with publish on crate.io, when you talk about binary it's only one binary (`cargo build --release`) or it's a binary by rust target `cargo build --release --target=$(rustup target list)`.

I also see github as a yml config for setting up [release notes automatically](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) based on some labels attached to pull requests.

**Comment by Daniel-Boll** [comment]
@gvieira18 

> Also, what do you guys think about the release flow? Is it full main branch, or do we have develop and main too, or do we just follow main but releases are requested manually through workflow_dispatch?

I think we can follow squashing things into the main branch and releases be triggered either by workflow_dispatch or by commits that matches versioning bumping, I do a similar thing on the [JS driver](https://github.com/Daniel-Boll/scylla-javascript-driver/blob/main/.github/workflows/CI.yml#L24-L39).

> when you talk about binary it's only one binary (cargo build --release) or it's a binary by rust target cargo build --release --target=$(rustup target list).

Publishing releases should probably consider some of the targets, like: `linux_aarch64, linux_armv6, linux_x86_64, windows_x86_64`

> I also see github as a yml config for setting up [release notes automatically](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) based on some labels attached to pull requests.

We also should try to integrate [git cliff](https://github.com/orhun/git-cliff) there is a [gh action](https://git-cliff.org/docs/github-actions/git-cliff-action) to run that.
